# Goal of the notebook

This is the most important notebook, since data is collected using it. NOTE THAT the data is collected for studying and research reasons only (no commercial goals !!!)!

We collect data every day until the necessary number of samples is collected, or there is no time left.

In [1]:
from yahoo_fin import options as op
import pandas as pd
import numpy as np

In [2]:
companies = ['AAPL', 
            'GOOGL',
            'MSFT',
            'SPY',
            'PFE',
            'LMT',
            'DIS',
            'VZ',
            'PYPL',
            'TSN',
            'DG',
            'QCOM',
            'META',
            'TSLA',
            'NFLX',
            'NVDA',
            'AMZN',
            'AVGO',
            'LLY',
            'JPM',
            'UNH',
            'V',
            'MA',
            'JNJ',
            'PG',
            'MRK',
            'MCD',
            'WMT',
            'BAC',
            'ACN',
            'KO',
            'PEP',
            'CSCO',
            'ORCL',
            'INTC']

In [4]:
# 34 companies and S&P 500
len(companies) - 1

34

In [3]:
# put down the date, so that we can save file and understand at what date the data was collected
current_date = '12 April'
dataset_all = pd.DataFrame()

In [4]:
# a script to collect data
for TICKER in companies:
    print(TICKER)
    ticker_data = pd.DataFrame()
    try:
        all_dates = op.get_expiration_dates(TICKER)
        for date in all_dates:
            df = op.get_calls(TICKER, date=date)
            df['Expiration date'] = date
            df['Company'] = TICKER
            df['Date of getting data'] = current_date
            ticker_data = ticker_data.append(df)

        ticker_data.index = np.arange(0, len(ticker_data))

        dataset_all = dataset_all.append(ticker_data)
        print('Success')
    except Exception as e:
        print('Error with this TICKER')
        print(str(e))
        pass
    #time.sleep(5)

AAPL
Success
GOOGL
Success
MSFT
Success
SPY
Success
PFE
Success
LMT
Success
DIS
Success
VZ
Success
PYPL
Success
TSN
Success
DG
Success
QCOM
Success
META
Success
TSLA
Success
NFLX
Success
NVDA
Success
AMZN
Success
AVGO
Success
LLY
Success
JPM
Success
UNH
Success
V
Success
MA
Success
JNJ
Success
PG
Success
MRK
Success
MCD
Success
WMT
Success
BAC
Success
ACN
Success
KO
Success
PEP
Success
CSCO
Success
ORCL
Success
INTC
Success

In [5]:
# save
dataset_all.to_csv(f'DATASETS/NEW_{current_date}.csv', index=False)

In [6]:
dataset_all

,Contract Name,Last Trade Date,Strike,Last Price,Bid,Ask,Change,% Change,Volume,Open Interest,Implied Volatility,Expiration date,Company,Date of getting data
0,AAPL240412C00100000,2024-04-12 10:50AM EDT,100.0,75.85,75.80,76.10,1.15,+1.54%,1,20,337.50%,"April 12, 2024",AAPL,12 April
1,AAPL240412C00105000,2024-03-15 12:24PM EDT,105.0,66.79,70.75,71.15,0.00,-,-,2,312.50%,"April 12, 2024",AAPL,12 April
2,AAPL240412C00120000,2024-04-08 10:30AM EDT,120.0,49.00,55.55,56.45,0.00,-,6,16,300.00%,"April 12, 2024",AAPL,12 April
3,AAPL240412C00125000,2024-04-05 3:33PM EDT,125.0,44.99,50.60,51.20,0.00,-,2,3,335.55%,"April 12, 2024",AAPL,12 April
4,AAPL240412C00130000,2024-04-11 3:18PM EDT,130.0,44.51,45.50,46.20,0.00,-,3,3,302.34%,"April 12, 2024",AAPL,12 April
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,INTC261218C00050000,2024-04-12 3:01PM EDT,50.0,5.70,5.55,5.80,-0.80,-12.31%,42,1420,42.66%,"December 18, 2026",INTC,12 April
488,INTC261218C00055000,2024-04-12 2:27PM EDT,55.0,4.80,4.70,4.80,-0.60,-11.11%,73,31727,42.29%,"December 18, 2026",INTC,12 April
489,INTC261218C00060000,2024-04-12 2:36PM EDT,60.0,3.95,3.80,4.05,-0.57,-12.61%,68,2618,42.29%,"December 18, 2026",INTC,12 April
490,INTC261218C00065000,2024-04-12 2:37PM EDT,65.0,3.30,2.52,3.35,-0.47,-12.47%,22,304,41.89%,"December 18, 2026",INTC,12 April
491,INTC261218C00070000,2024-04-12 2:57PM EDT,70.0,2.75,2.72,2.80,-0.35,-11.29%,169,2398,41.66%,"December 18, 2026",INTC,12 April

### Complete