# Goal of the notebook

Remember that I had to collect data every day to make it historical (because in Yahoo one cannot get historical data on options). Hence, this notebook is required to put all data into a single file.

In [108]:
import pandas as pd
import numpy as np

In [109]:
# put down all the files with data
paths = ['DATASETS/NEW_16 February.csv', 'DATASETS/NEW_19 February.csv', 'DATASETS/NEW_20 February.csv',
        'DATASETS/NEW_21 February.csv', 'DATASETS/NEW_22 February.csv', 'DATASETS/NEW_23 February.csv',
        'DATASETS/NEW_26 February.csv', 'DATASETS/NEW_27 February.csv', 'DATASETS/NEW_28 February.csv',
        'DATASETS/NEW_29 February.csv', 'DATASETS/NEW_1 March.csv', 'DATASETS/NEW_2 March.csv', 
        'DATASETS/NEW_4 March.csv', 'DATASETS/NEW_5 March.csv', 'DATASETS/NEW_6 March.csv',
        'DATASETS/NEW_7 March.csv', 'DATASETS/NEW_8 March.csv',
        'DATASETS/NEW_11 March.csv', 'DATASETS/NEW_12 March.csv', 'DATASETS/NEW_13 March.csv',
        'DATASETS/NEW_14 March.csv', 'DATASETS/NEW_15 March.csv',
        'DATASETS/NEW_18 March.csv', 'DATASETS/NEW_19 March.csv', 'DATASETS/NEW_20 March.csv',
        'DATASETS/NEW_21 March.csv', 'DATASETS/NEW_22 March.csv',
        'DATASETS/NEW_25 March.csv', 'DATASETS/NEW_26 March.csv', 'DATASETS/NEW_27 March.csv',
         'DATASETS/NEW_28 March.csv', 'DATASETS/NEW_29 March.csv',
        'DATASETS/NEW_1 April.csv', 'DATASETS/NEW_2 April.csv', 'DATASETS/NEW_3 April.csv', 'DATASETS/NEW_4 April.csv',
        'DATASETS/NEW_8 April.csv', 'DATASETS/NEW_9 April.csv', 'DATASETS/NEW_10 April.csv',
        'DATASETS/NEW_11 April.csv', 'DATASETS/NEW_12 April.csv']

In [110]:
# a function that takes all file paths and constructs a single file
def get_data(datasets_paths):
    dataset_full = pd.DataFrame()
    for path in datasets_paths:
        df = pd.read_csv(path)
        dataset_full = dataset_full.append(df)
    dataset_full.index = np.arange(0, len(dataset_full))
    return dataset_full

In [111]:
dataset_full = get_data(paths)

In [112]:
# drop the unnecessary column
dataset_full = dataset_full.drop('0', axis=1)
dataset_full

,Contract Name,Last Trade Date,Strike,Last Price,Bid,Ask,Change,% Change,Volume,Open Interest,Implied Volatility,Expiration date,Company,Date of getting data
0,AAPL240223C00095000,2024-02-15 10:56AM EST,95.0,86.97,87.1,87.6,0.00,-,1,7,177.34%,"February 23, 2024",AAPL,16 February
1,AAPL240223C00100000,2024-02-16 3:20PM EST,100.0,82.27,82.1,82.65,0.06,+0.07%,1,9,173.44%,"February 23, 2024",AAPL,16 February
2,AAPL240223C00110000,2024-01-22 12:07PM EST,110.0,83.50,72.1,72.65,0.00,-,-,1,148.05%,"February 23, 2024",AAPL,16 February
3,AAPL240223C00115000,2024-02-14 3:52PM EST,115.0,66.87,67.1,67.65,-2.18,-3.16%,1,2,135.94%,"February 23, 2024",AAPL,16 February
4,AAPL240223C00120000,2024-02-15 3:57PM EST,120.0,64.40,62.1,62.65,0.00,-,6,3,124.61%,"February 23, 2024",AAPL,16 February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1223326,INTC261218C00050000,2024-04-12 3:01PM EDT,50.0,5.70,5.55,5.8,-0.80,-12.31%,42,1420,42.66%,"December 18, 2026",INTC,12 April
1223327,INTC261218C00055000,2024-04-12 2:27PM EDT,55.0,4.80,4.7,4.8,-0.60,-11.11%,73,31727,42.29%,"December 18, 2026",INTC,12 April
1223328,INTC261218C00060000,2024-04-12 2:36PM EDT,60.0,3.95,3.8,4.05,-0.57,-12.61%,68,2618,42.29%,"December 18, 2026",INTC,12 April
1223329,INTC261218C00065000,2024-04-12 2:37PM EDT,65.0,3.30,2.52,3.35,-0.47,-12.47%,22,304,41.89%,"December 18, 2026",INTC,12 April
1223330,INTC261218C00070000,2024-04-12 2:57PM EDT,70.0,2.75,2.72,2.8,-0.35,-11.29%,169,2398,41.66%,"December 18, 2026",INTC,12 April

In [113]:
dataset_full = dataset_full.drop_duplicates()
dataset_full

,Contract Name,Last Trade Date,Strike,Last Price,Bid,Ask,Change,% Change,Volume,Open Interest,Implied Volatility,Expiration date,Company,Date of getting data
0,AAPL240223C00095000,2024-02-15 10:56AM EST,95.0,86.97,87.1,87.6,0.00,-,1,7,177.34%,"February 23, 2024",AAPL,16 February
1,AAPL240223C00100000,2024-02-16 3:20PM EST,100.0,82.27,82.1,82.65,0.06,+0.07%,1,9,173.44%,"February 23, 2024",AAPL,16 February
2,AAPL240223C00110000,2024-01-22 12:07PM EST,110.0,83.50,72.1,72.65,0.00,-,-,1,148.05%,"February 23, 2024",AAPL,16 February
3,AAPL240223C00115000,2024-02-14 3:52PM EST,115.0,66.87,67.1,67.65,-2.18,-3.16%,1,2,135.94%,"February 23, 2024",AAPL,16 February
4,AAPL240223C00120000,2024-02-15 3:57PM EST,120.0,64.40,62.1,62.65,0.00,-,6,3,124.61%,"February 23, 2024",AAPL,16 February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1223326,INTC261218C00050000,2024-04-12 3:01PM EDT,50.0,5.70,5.55,5.8,-0.80,-12.31%,42,1420,42.66%,"December 18, 2026",INTC,12 April
1223327,INTC261218C00055000,2024-04-12 2:27PM EDT,55.0,4.80,4.7,4.8,-0.60,-11.11%,73,31727,42.29%,"December 18, 2026",INTC,12 April
1223328,INTC261218C00060000,2024-04-12 2:36PM EDT,60.0,3.95,3.8,4.05,-0.57,-12.61%,68,2618,42.29%,"December 18, 2026",INTC,12 April
1223329,INTC261218C00065000,2024-04-12 2:37PM EDT,65.0,3.30,2.52,3.35,-0.47,-12.47%,22,304,41.89%,"December 18, 2026",INTC,12 April
1223330,INTC261218C00070000,2024-04-12 2:57PM EDT,70.0,2.75,2.72,2.8,-0.35,-11.29%,169,2398,41.66%,"December 18, 2026",INTC,12 April

In [114]:
# save data
dataset_full.to_csv('Raw_data_02_05.csv', index=None)

### Completed